accordion:
  - title: Which licences and permits can I apply for here?
    content: |
      With our Guided Journey feature, you can apply for the following licences from these government agencies:

      - Change of Use / Lodgement - URA
      - Change of Trade - HDB
      - Food Shop Licence, Food Stall Licence - SFA
      - Petroleum & Flammable Material Storage Licence - SCDF
      - Liquor Licence and Public Entertainment Licence - SPF
      - Tobacco Retail Licence - HSA
      - Halal Certification - MUIS

      If the licences you need are not on this list, please apply for your licences with [GoBusiness Licensing](https://licence1.business.gov.sg/feportal/web/frontier/home){:target="_blank"}{:rel="noopener"}.

  - title: How do I know which Food Shop type my business falls under?
    content: |
      Here is a [list of all Food Shop types](/images/grow/FoodShopTypeMapping.pdf){:target="_blank"} and their descriptions.

      If you are not sure, simply use our Guided Journey feature and answer a series of questions about your business to find out which Food Shop type it falls under.

  - title: Why are some licences incompatible?
    content: |
      Some licences are mutually exclusive and cannot be applied for together. Here is a list of incompatible licences:

      1. Halal Certification is mutually exclusive to Liquor Licence and Tobacco Licence.
      2. The Liquor Licence and Public Entertainment Licence may not be compatible with certain food shop types (e.g. Canteen)

  - title: Do I enter the name of my shop or the name of my registered business under 'Premises Name'?
    content: |
      You will need to enter the name of your shop under 'Premises Name'. This means the name you plan to display on your shopfront.

  - title: My premises address does not have a level and/or unit number. What should I do?
    content: |
      If your premises address does not have a level and/or unit number, please enter '00' under 'Level' and 'Unit Number' to proceed.

  - title: What is a Food Shop type?
    content: |
      The Singapore Food Agency (SFA) classifies food & beverage businesses according to their business concept.

      Here is a [list of all Food Shop types](https://go.gov.sg/food-shop-types){:target="_blank"}{:rel="noopener"}.

  - title: How do I check on the status of my application?
    content: |
      All application status updates will be sent to the e-mail address provided in the application form.

      You can also check on each licence's current status on your Application Journey.

  - title: Why are some supporting documents under 'Submit Now' and others are under 'Submit For Later'?
    content: |
      Documents under 'Submit Now' will need to be uploaded once you submit your application, as they are required to start processing it.

      Documents under 'Submit For Later' will only be needed at a later stage, and can be submitted in future via e-mail. However, you can choose to upload them together with your application, if you'd prefer.

  - title: What is an Application Journey?
    content: |
      An Application Journey shows the correct order to apply for your licences in order to start running your business. It is customized based on your business concept.

  - title: Why can't I apply for some of the licences in my Application Journey?
    content: |
      Some licences are required before you can apply for others. Based on this, the Application Journey shows you the correct order to apply for them and tells you which licences you will need before applying for the next one.

      Licences indicated in grey require you to obtain another licence first before you can proceed.

  - title: What falls under 'Others' in Food Shop Type?
    content: |
      Out of the Food Shop types recommended for you, you are advised to select the option that best describes your business concept. If none of the options apply, you may select 'Others'.

  - title: Why can't I select more than one Food Shop type?
    content: |
      Each premises is only allowed to have one Food Shop type.

  - title: How and when do I submit the supporting documents under 'Submit For Later'?
    content: |
      An officer from the respective government agency will be in touch to request for the documents, which you can submit via e-mail.

  - title: How do I find out the supporting documents I need for each licence?
    content: |
      Clicking on each licence in your Application Journey will show a list of supporting documents required. You can also refer to a full list of supporting documents on the 'Required Documents for your Licences' sidebar, located on the right side of your Application Journey.

  - title: What does 'licence dependency' mean?
    content: |
      Some licences are required before you can apply for others. Based on this, the Guided Journey feature maps out the correct order to apply for them and shows you which licences you will need before applying for the next one.

      <u>Here are the licence dependencies you may see</u>

      1. SFA's Food Shop Licence and SPF's Public Entertainment Licence and Liquor Licence are dependent on landowner's permission (i.e. URA, HDB, Private, SLA, JTC etc)

      2. Halal Certification is dependent on Food Shop Licence approval.

  - title: What does 'Premises' mean?
    content: |
      'Premises' refers to the food shop you would like to obtain licences for.

  - title: I have accidentally added a new premises, how can I delete the draft application/premises?
    content: |
      Login to [GoBusiness Guided Journey](https://foodservices.gobusiness.gov.sg/licences/foodservices?src=licensing_faqs){:target="_blank"}{:rel="noopener"}. Click on the premises you would like to delete. If the premises can be deleted, the “Remove” button will appear beside the “Premises Details” section title. Click on the “Remove” button to start the process of deletion.

      A Premises can be deleted if it only contains draft application(s).

      Note: Deleted premises as well as their draft applications are not recoverable.

  - title: What does 'adjacent unit' mean?
    content: |
      Adjacent units are multiple units next to each other. This applies to businesses occupying multiple units. If your business occupies multiple levels without a connecting staircase within your premises, you will need to apply for individual licences for each level.
