accordion:
  - title: Where can I check the status of my application?
    content: |
      Log in to Business Grants Portal and navigate to 'My Grants'. You'll see the status of all your grant applications on this page. Notification emails are also sent to the main contact person as the application moves through the process.

      For further enquiries, you may also contact your processing agency. To find the agency's contact details, navigate to 'My Grants' on the Business Grants Portal and click on the project title of the application.

  - title: How long does it take for my application to process?
    content: |
      It can take between 4 to 10 weeks for a grant application to process.

  - title: How can I cancel my application?
    content: |
      If the processing agency has returned your application for edit, you may click on 'Cancel Application'.

      However, if your application is submitted and is being processed by the agency, you will need to email the processing agency to cancel your application.
